language: php

notifications:
  email:
    recipients:

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1

addons:
  postgresql: "9.6"

services:
  - mysql

env:
  global:
    - DB=pgsql
  matrix:
    - MOODLE_BRANCH=MOODLE_30_STABLE
    - MOODLE_BRANCH=MOODLE_31_STABLE
    - MOODLE_BRANCH=MOODLE_32_STABLE
    - MOODLE_BRANCH=MOODLE_33_STABLE
    - MOODLE_BRANCH=MOODLE_34_STABLE
    - MOODLE_BRANCH=MOODLE_35_STABLE
    - MOODLE_BRANCH=master

matrix:
  include:
    # Test older Moodles only with PHP 5.6
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_27_STABLE
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_28_STABLE
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_29_STABLE
    # Test with MySQL
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=master
  exclude:
    - php: 5.6
      env: MOODLE_BRANCH=master
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_34_STABLE
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.0
      env: MOODLE_BRANCH=master
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_30_STABLE
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_31_STABLE

before_install:
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv

script:
  - moodle-plugin-ci validate
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
